config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :user_logout
      get :user_signup
      get :user_products
    end

    member do
      get :identification
    end
  end

  resources :products do
    resource :product_comments, only: [:create]
    post 'my_product_comments'=> 'product_comments#my_product_comments'
    collection do
      get :confirm
      get :search
      get :get_category_children, defaults: { format: 'json' }
      get :get_category_grandchildren, defaults: { format: 'json' }
      get :get_size, defaults: { format: 'json' }
    end
    member do
      get :purchase
      patch :bought
      get :my_show
      get :unpublished
      get :sell
      get :get_size, defaults: { format: 'json' }
    end
  end

  namespace :api do
    resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

  resources :creditcards, only: [:index, :new, :show, :destroy, :create]

  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :user_detail
  has_one :user_address
  has_one :creditcard
  has_many :products
  validates :nickname, presence: true
  has_many :product_comments,dependent: :destroy

 # userが「買った商品 :buyed_products」「現在売っている商品 :saling_items」「すでに売った商品 :sold_items」
  has_many :buyed_products, foreign_key: "buyer_id", class_name: "Product"
  has_many :saling_products, -> { where("buyer_id is NULL") }, foreign_key: "user_id", class_name: "Product"
  has_many :sold_products, -> { where("buyer_id is not NULL") }, foreign_key: "user_id", class_name: "Product"

  accepts_nested_attributes_for :user_address, :user_detail, :creditcard
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google_oauth2
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_sign_up_params, only: [:create]

  def new
    @user = User.new
    @user.build_user_address
    @user.build_user_detail
    @user.build_creditcard
  end

  def create
    @user = User.new(sign_up_params)
    if @user.save
      sign_in @user
    else
      # flash[:notice] = "メールアドレスに誤りがあります。ご確認いただき、正しく変更してください。"
      render :new
    end

  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |params|
      params.permit(:email, :password, :password_confirmation, :current_password, :nickname,
                    user_detail_attributes: [:user_id, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day, :mobile_phone],
                    user_address_attributes: [:user_id, :postal_code, :city, :block_number, :building, :telephone, :prefecture],
                    creditcard_attributes: [:user_id, :card_number, :valid_month, :valid_year, :security_code])
    end
  end

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_user, only: [:edit, :identification, :update]

  def index
  end

  def identification
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
    @user.update!(user_params)
    redirect_to identification_user_path(current_user)
  end
  
  def user_products
    @products = Product.where(user_id: current_user.id)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, user_address_attributes:[:id, :postal_code, :prefecture,  :city, :block_number, :building])
  end
end

app/views/users/_users_product.html.haml
%li
  = link_to my_show_product_path(users_product), class: "notification-list__link" do
    %figure
      = image_tag(users_product.images.first.name)
    .notification-list__body
      .notification-list__body__text
        = users_product.name
      .listing-item-count
        %i.far.fa-heart
        %span 0
      .listing-item-count
        %i.far.fa-comment-alt
        %span 0
      .mypage-item-status
        - if users_product.status == "sell"
          %p.mypage-item-status__sell
            出品中
        - elsif users_product.status == "unpublished"
          %p.mypage-item-status__unpublished
            公開停止中
      = fa_icon "angle-right"

app/views/users/card.html.haml
= render 'shared/top-header'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      .registration-container
        %h2.card-head
          支払い方法
        .registration-container__card
          %section
            .card-content
              %h3
                クレジットカード一覧
          %section.add-card
            .add-card__content
              = link_to "card_create" ,class: "btn-card btn-signin" do
                %i.fas.fa-credit-card
                クレジットカードを追加する
          .about-payment
            = link_to "#" ,class: "about-payment-link" do
              支払い方法について
              %i.fas.fa-angle-right

    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'

app/views/users/edit.html.haml
- breadcrumb :profile
= render 'shared/top-header'
= render 'shared/breadcrumbs'

.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %section.mypage-detail-container
        %h2.mypage-detail-head プロフィール
        %form{action: "https://www.mercari.com/jp/mypage/profile/", method: "POST"}
          .setting-profile-icon
            %figure
              = image_tag("icon.png", height: "60", width: "60")
            %input{type: "text", class: "input-default", value: @user.nickname}
          .setting-profile-content
            %textarea{class:"textarea-default", name: "introduction", placeholder: "例)こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
            = button_tag '変更する', class: 'btm_update'
    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'

app/views/users/identification.html.haml
- breadcrumb :identification
=render 'shared/top-header'
=render 'shared/breadcrumbs'

.identification-main
  .identification-container
    .identification-wrapper
      %h2.identification-title 本人情報の登録
      .identification-form
        = form_for @user, class: "identification-form" do |f|
          = render "devise/shared/error_messages", resource: resource
          .identification-form__instruction
            %p.identification-form__instruction--text お客さまの本人情報をご登録ください。<br>登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。

          =link_to("#", class: "identification-form__link  ") do
            = fa_icon 'chevron-right', class: "identification-form__link--arrow-right"
            .identification-form__link--text 本人確認書類のアップロードについて

          .identification-form__group
            %label.identification-form__group--title お名前
            %p.identification-form__group--text
              = @user.nickname

          .identification-form__group
            %label.identification-form__group--title お名前カナ
            %p.identification-form__group--text
              = (@user.user_detail.last_name_kana + " " + @user.user_detail.first_name_kana)

          .identification-form__group
            %label.identification-form__group--title 生年月日
            %p.identification-form__group--text
              = (@user.user_detail.birth_year.to_s + "/" + @user.user_detail.birth_month.to_s + "/" + @user.user_detail.birth_day.to_s)

          = form_for @user, class: "identification-form" do |f|
            = f.fields_for :user_address do |i|
              .identification-form__group
                %label.identification-form__group--title 郵便番号
                %span.optional 任意
                = i.text_field :postal_code, class: "identification-form__group--textarea", placeholder: '例)1234567'

              .identification-form__group
                %label.identification-form__group--title 都道府県
                %span.optional 任意
                = i.text_field :prefecture, class: "identification-form__group--textarea", placeholder: '--'

              .identification-form__group
                %label.identification-form__group--title 市区町村
                %span.optional 任意
                = i.text_field :city, class: "identification-form__group--textarea", placeholder: '例)横浜市緑区'

              .identification-form__group
                %label.identification-form__group--title 番地
                %span.optional 任意
                = i.text_field :block_number, class: "identification-form__group--textarea", placeholder: '例)1-1-1'

              .identification-form__group
                %label.identification-form__group--title 建物名
                %span.optional 任意
                = i.text_field :building, class: "identification-form__group--textarea", placeholder: '例)柳ビル103'

              .identification-form__group
                = f.submit class: "identification-form__group--button", value: "登録する"
                -# %input{type: "button", class: "identification-form__group--button", value: "登録する"}
          
          =link_to("#", class: "identification-form__last") do
            = fa_icon 'chevron-right', class: "identification-form__last--arrow-right"
            .identification-form__last--text 本人情報の登録について
    =render 'shared/mypage-sidemenu'
=render 'shared/banner'
=render 'shared/top-footer'
=render 'shared/sell-btn'

app/views/users/index.html.haml
- breadcrumb :mypage
= render "shared/top-header"
= render 'shared/breadcrumbs'

.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %section.mypage-user-icon
        = link_to "#" do
          %figure
            = image_tag "icon.png", alt: "ユーザーアイコン", alt: "ユーザーアイコン", height: "60", width: "60"
          %h2.bold
            = current_user.nickname
          .mypage-number
            %p
              評価
              %span.bold 0
            %p.right
              出品数
              %span.bold 0
      %section.mypage-todo
        %ul.mypage-tabs.up
          %li.notification.is-active
            %h3 お知らせ
          %li.todo
            %h3 やることリスト
        %ul.tab-content
          %ul.notification-list.tab
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "mercari_name.png"
                .notification-list__body
                  .notification-list__body__text【7日間限定】10人に1人最大P6,000もらえるキャンペーン開始
                  %time
                    %i.far.fa-clock
                    %span 22 時間前
                = fa_icon "angle-right"
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "mercari_name.png"
                .notification-list__body
                  .notification-list__body__text 事務局から個別メッセージ「ログイン通知」
                  %time
                    %i.far.fa-clock
                    %span 1 日前
                = fa_icon "angle-right"
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "mercari_name.png"
                .notification-list__body
                  .notification-list__body__text 事務局から個別メッセージ「【重要】新サービス開始に伴う利用規約改訂のお知らせ」
                  %time
                    %i.far.fa-clock
                    %span 16 日前
                = fa_icon "angle-right"
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "mercari_name.png"
                .notification-list__body
                  .notification-list__body__text 【あと3日】対象カテゴリーが売れたら“必ず“ポイントがもらえるキャンペーン開催中
                  %time
                    %i.far.fa-clock
                    %span 21 日前
                = fa_icon "angle-right"
            %li.notification-list__all
              = link_to "#" do
                一覧を見る
          %ul.todo-list.tab
            %li.hide.mypage-item-not-found
              現在、やることリストはありません
      %section.mypage-tab-trading-traded
        %h2.mypage-tab-head 購入した商品
        %ul.mypage-tabs.under
          %li.trading.is-action
            %h3 取引中
          %li.traded
            %h3 過去の取引
        %ul.tab-content
          %ul.trading-list.ta
            %li.trading-item-not-found.bold 
              取引中の商品がありません
          %ul.traded-list.ta
            %li.traded-item-not-found
              過去に取引した商品がありません
    = render 'shared/mypage-sidemenu'

= render "shared/banner"
= render "shared/top-footer"
=render 'shared/sell-btn'

app/views/users/new.html.haml
.sign-in-container
  .single-container
    = render "devise/sessions/header"
    .single-main
      .registration-container
        %h2.registration-head
          新規会員登録
        .registration-container__form
          .registration-container__form__container
            = link_to new_user_registration_path ,class: "btn-default btn-red-mail" do
              %i.far.fa-envelope              
              メールアドレスで登録する
            %button.btn-default.btn-fb
              %i.fab.fa-facebook-square
              Facebookで登録する
            %button.btn-default.btn-go
              = image_tag("google.png", size: "20x20", class: "google-icon")
              Googleで登録する
    = render "devise/registrations/footer"

app/views/users/user_logout.html.haml
- breadcrumb :logout
= render 'shared/top-header'
= render 'shared/breadcrumbs'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %section.mypage-logout-container
        .mypage-logout-content
          = button_to destroy_user_session_path,class: 'user-logout-btn',method: :delete do
            ログアウト
    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'

app/views/users/user_products.html.haml
- breadcrumb :user_products
= render "shared/top-header"
= render "layouts/flash"
= render 'shared/breadcrumbs'

.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %section.mypage-tab-saling
        %h2.mypage-tab-head 出品した商品
      %section.mypage-todo
        %ul.mypage-tabs.up
          %li.notification.is-active
            %h3 出品中
          %li.todo
            %h3 取引中
        %ul.tab-content
          %ul.notification-list.tab
            = render partial: "users_product", collection: @products
        %ul.todo-list.tab
          %li.hide.mypage-item-not-found
            取引中の商品がありません
    = render 'shared/mypage-sidemenu'

= render "shared/banner"
= render "shared/top-footer"

app/views/users/user_signup.haml
.sign-in-container
  .single-container
    = render "devise/sessions/header"
    .single-main
      .registration-container
        %h2.registration-head
          新規会員登録
        .registration-container__form
          .registration-container__form__container
            = link_to "sign_up" ,class: "btn-default btn-red-mail" do
              %i.far.fa-envelope              
              メールアドレスで登録する
            %button.btn-default.btn-fb
              %i.fab.fa-facebook-square
              Facebookで登録する
            %button.btn-default.btn-go
              = image_tag("google.png", size: "20x20", class: "google-icon")
              Googleで登録する
    = render "devise/registrations/footer"

app/views/users/userlogout.html.haml
= render 'shared/top-header'
= render 'shared/breadcrumbs'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %section.mypage-logout-container
        .mypage-logout-content
          = button_to destroy_user_session_path,class: 'user-logout-btn',method: :delete do
            ログアウト
    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'

app/views/users/usersignup.haml
.sign-in-container
  .single-container
    = render "devise/sessions/header"
    .single-main
      .registration-container
        %h2.registration-head
          新規会員登録
        .registration-container__form
          .registration-container__form__container
            = link_to "sign_up" ,class: "btn-default btn-red-mail" do
              %i.far.fa-envelope              
              メールアドレスで登録する
            %button.btn-default.btn-fb
              %i.fab.fa-facebook-square
              Facebookで登録する
            %button.btn-default.btn-go
              = image_tag("google.png", size: "20x20", class: "google-icon")
              Googleで登録する
    = render "devise/registrations/footer"