config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :user_logout
      get :user_signup
      get :user_products
    end

    member do
      get :identification
    end
  end

  resources :products do
    resource :product_comments, only: [:create]
    post 'my_product_comments'=> 'product_comments#my_product_comments'
    collection do
      get :confirm
      get :search
      get :get_category_children, defaults: { format: 'json' }
      get :get_category_grandchildren, defaults: { format: 'json' }
      get :get_size, defaults: { format: 'json' }
    end
    member do
      get :purchase
      patch :bought
      get :my_show
      get :unpublished
      get :sell
      get :get_size, defaults: { format: 'json' }
    end
  end

  namespace :api do
    resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

  resources :creditcards, only: [:index, :new, :show, :destroy, :create]

  resources :categories, only: [:index, :show]
end

app/views/shared/_banner.html.haml
.banner
  = image_tag 'bottom-banner.png', alt: '', height: '260px', width: '100%', class: 'banner-wrapper'
  .banner-content
    .banner-content__sub-title
    .banner-content__title
    .banner-content__icon
      .banner-content__icon--mercari
      .banner-content__icon--app-store
      .banner-content__icon--android
  .banner-image

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs
  .breadcrumbs-content
    = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/shared/_campaign_banner.html.haml
%section.slide-banner.owl-carousel
  = link_to root_path, class: "slide-banner__link slide-banner__link--camp" do
    = image_tag("camp-banner.png")
  = link_to root_path, class: "slide-banner__link slide-banner__link--register" do
    = image_tag("register_banner.png")
  = link_to root_path, class: "slide-banner__link slide-banner__link--anniversary" do
    = image_tag("banner-thanks.png")

app/views/shared/_comment.html.haml
- if comment.user.id == current_user.id
  %li.messeage-coments2
    .message-user2
      = link_to "#", class: "product-detail__middle__comments-box__avatar2" do
        %figure
          .unknown
            = image_tag("user-icon.svg", size: "32x32")
          %figcaption.bold #{comment.user.nickname}
    .message-body2
      .message-body__text
        = simple_format(comment.comment)
      .message-body__icon__left
        %time
          %i.far.fa-clock
          %span(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at)
          前
      .message-body__icon__right
        = link_to "" do
          %i.far.fa-flag
- else
  %li.messeage-coments
    .message-user
      = link_to "#", class: "product-detail__middle__comments-box__avatar" do
        %figure
          .message-user__unknown
            = image_tag("user-icon.svg", size: "32x32")
          %figcaption.bold #{comment.user.nickname}
        - if comment.user.id == @product.user_id
          .message-seller
            出品者
    .message-body
      .message-body__text
        = simple_format(comment.comment)
      .message-body__icon__left
        %time
          %i.far.fa-clock
          %span(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at)
          前
      .message-body__icon__right
        = link_to "" do
          %i.far.fa-flag 

app/views/shared/_common-header.html.haml
%header.single-header
  %h1
    =link_to '#' do
      = image_tag "logo.svg"

app/views/shared/_mini_mypage.html.haml
.header-mypage-box
  .mypage-box-top
    .mypage-box-top__image
      = image_tag "mypage_image.jpg", height: "80", width: "330"
      .mypage-box-top__image--icon
        = image_tag "icon.png", alt: "ユーザーアイコン", alt: "ユーザーアイコン", height: "60", width: "60"
        
    .mypage-box-top__text
      %h2.mypage-box-top__text--name
        = current_user.nickname
      .mypage-box-top__text--index
        %p.mypage-box-top__text--index-left
          評価
          %span.bold 0
        %p.mypage-box-top__text--index-right
          出品数
          %span.bold 0
    
    .mypage-box-top__sales
      .mypage-box-top__sales--balance
        .mypage-box-top__sales--balance-left 残高
        = fa_icon "angle-right", class: "mypage-box-top__sales--balance-arrow"
        .mypage-box-top__sales--balance-right ￥10,000

      .mypage-box-top__sales--point
        .mypage-box-top__sales--point-left ポイント
        = fa_icon "angle-right", class: "mypage-box-top__sales--point-arrow"
        .mypage-box-top__sales--point-right P 1000



  .mypage-box-down
    .mypage-box-down__list
      %li.mypage-box-down__list__link
        =link_to "#", class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            いいね！ 一覧
            = fa_icon "angle-right"
      %li.mypage-box-down__list__link
        =link_to user_products_users_path, class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            出品した商品-出品中
            = fa_icon "angle-right"
      %li.mypage-box-down__list__link
        =link_to "#", class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            出品した商品-取引中
            = fa_icon "angle-right"
      %li.mypage-box-down__list__link
        =link_to "#", class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            出品した商品-売却済み
            = fa_icon "angle-right"
      %li.mypage-box-down__list__link
        =link_to "#", class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            購入した商品-取引中
            = fa_icon "angle-right"
      %li.mypage-box-down__list__link
        =link_to "#", class: "mypage-box-down__list__link__area" do
          %p.mypage-box-down__list__link__area__name
            購入した商品-過去の取引
            = fa_icon "angle-right"

app/views/shared/_mypage-sidemenu.html.haml
.l-side
  %ul.l-side__list
    %li.l-side__list__link
      =link_to users_path, class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          マイページ
          = fa_icon "angle-right"

    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          お知らせ
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          やることリスト
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          いいね！ 一覧
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to new_product_path, class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          出品する
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to user_products_users_path, class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          出品した商品-出品中
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          出品した商品-取引中
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          出品した商品-売却済み
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          購入した商品-取引中
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          購入した商品-過去の取引
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          ニュース一覧
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          評価一覧
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          ガイド
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          お問い合わせ
          = fa_icon "angle-right"


  %h3.mypage-nav-head
    メルペイ
  %ul.l-side__list.under-list
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          売上・振込申請
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          ポイント
          = fa_icon "angle-right"
  %h3.mypage-nav-head
    設定
  %ul.l-side__list.under-list
    %li.l-side__list__link
      =link_to edit_user_path(current_user), class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          プロフィール
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          発送元・お届け先住所変更
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to creditcards_path, class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          支払い方法
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          メール/パスワード
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to identification_user_path(current_user), class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          本人情報
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to "#", class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          電話番号の確認
          = fa_icon "angle-right"
    %li.l-side__list__link
      =link_to user_logout_users_path, class: "l-side__list__link__area" do
        %p.l-side__list__link__area__name
          ログアウト
          = fa_icon "angle-right"

app/views/shared/_second_header.haml
.main-header
  %h1
    = link_to root_path do
      = image_tag 'mercarinew.png'

app/views/shared/_sell-btn.html.haml
=link_to new_product_path ,class: "sell-btn" do
  .btn-wrapper
    .btn-wrapper__title 出品
    = fa_icon 'camera', class: "camera__icon"

app/views/shared/_top-footer.html.haml
.top-footer
  .footer-top
    .footer__official
      %h2.footer__official__title  メルカリについて
      %ul 
        %li 会社概要(運営会社)
        %li 採用情報
        %li プレスリリース
        %li 公式ブログ
        %li メルカリロゴ利用ガイドライン

      .footer__official--icon
        %i.fab.fa-twitter.twitter
        %i.fab.fa-facebook-square.facebook

    .footer__guide
      %h2.footer__guide__title  ヘルプ&ガイド
      %ul 
        %li メルカリガイド
        %li らくらくメルカリ便
        %li ゆうゆうメルカリ便
        %li 大型メルカリ便
        %li 車体取引ガイド
        %li メルカリあんしん・あんぜん宣言!
        %li 偽ブランド品撲滅への取り組み
        %li メルカリボックス

    .footer__rules
      %h2.footer__rules__title プライバシーと利用規約

      .inner
        .inner-left
          %ul 
            %li プライバシーポリシー
            %li メルカリ利用規約
            %li あんしんスマホサポート制度に関する利用特約
            %li コンプライアンスポリシー

        .inner-right
          %ul 
            %li 個人データのあんぜん管理に係る基本方針
            %li 特定商取引に関する表記
            %li 資金決済法に基づく表示
            %li 法令遵守と犯罪抑止のために
            %li 返品・返金ポリシー

    .footer__national
      %h2.footer__national__title  国
      %ul 
        %li 日本
        %li United States

  .footer-bottom
    .footer-bottom__logo
    =image_tag("logo-white.svg", size: "124x33")

    .footer-bottom__copy-right ©2019mercari

app/views/shared/_top-header.html.haml
.top-header
  .header-in
    .header-top
      .header-logo
        = link_to image_tag("mercari_logo.svg"),root_path

      .header-search
        = form_tag('/products/search',class: "header-search__input", method: :get) do
          %input.header-search__input--text{name: "keyword", placeholder: "何かお探しですか?", type: "text", value: ""}/
          %button.header-search__input--icon{title: "検索", type: "submit"}
            = fa_icon 'search', class: "search"
            %span<>
    
    .header-bottom
      .h-left
        =link_to categories_path,class: "category-search" do
          = fa_icon 'list', class: "category-search__icon"
          %h2.category-search__title カテゴリーから探す
        =render 'products/category-search'

        =link_to "#",class: "brand-search" do
          = fa_icon 'tag', class: "brand-search__icon"
          %h2.brand-search__title ブランドから探す
        =render 'products/brand-search'

      .h-right
        - if user_signed_in?
          .h-right__list
            =link_to "",class: "good-index" do
              %i.far.fa-heart.top-page__icon
              %span.good-index__title いいね!一覧
          .h-right__list
            =link_to "",class: "notification" do
              %i.far.fa-bell.top-page__icon
              %span.notification__title お知らせ
          .h-right__list
            =link_to "",class: "todo" do
              %i.fa.fa-check.top-page__icon
              %span.todo__title やることリスト
          .h-right__list
            =link_to users_path,class: "top-mypage" do
              = image_tag("icon.png", class: "top-mypage__image")
              %span.top-mypage__text マイページ
            = render 'shared/mini_mypage'
        - else
          = link_to "新規会員登録", new_user_path, class: 'signin__button'
          = link_to "ログイン", new_user_session_path, class: 'login__button'