config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :user_logout
      get :user_signup
      get :user_products
    end

    member do
      get :identification
    end
  end

  resources :products do
    resource :product_comments, only: [:create]
    post 'my_product_comments'=> 'product_comments#my_product_comments'
    collection do
      get :confirm
      get :search
      get :get_category_children, defaults: { format: 'json' }
      get :get_category_grandchildren, defaults: { format: 'json' }
      get :get_size, defaults: { format: 'json' }
    end
    member do
      get :purchase
      patch :bought
      get :my_show
      get :unpublished
      get :sell
      get :get_size, defaults: { format: 'json' }
    end
  end

  namespace :api do
    resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

  resources :creditcards, only: [:index, :new, :show, :destroy, :create]

  resources :categories, only: [:index, :show]
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user, optional: true

  validates :card_number, presence: true,
                          format: {
                              with: /\A(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6011[0-9]{12}|3(?:0[0-5]|[68][0-9])[0-9]{11}|3[47]{13}|(?:2131|1800|35[0-9]{3})[0-9]{11})\z/,
                              message: "半角数字のみで入力して下さい"
                            }
  validates :valid_month, presence: true
  validates :valid_year, presence: true
  validates :security_code, presence: true, length: { in: 3..4 },
                            format: {
                              with: /\A[0-9]+\z/,
                              message: "半角数字のみで入力して下さい"
                            }
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_creditcard, only: [:show, :destroy]

  def index
    card = current_user.creditcard
    redirect_to creditcard_path(card) unless card.blank?
  end

  def new
    @creditcard = Creditcard.new
  end

  def show
    redirect_to action: "new" if @creditcard.blank?
  end

  def create
    @creditcard = Creditcard.new(new_params)
    if @creditcard.save
      redirect_to creditcards_path
    else
      render :new
    end
  end

  def destroy
    if @creditcard.blank?
      redirect_to action: "new"
    else
      @creditcard.delete if @creditcard.user_id == current_user.id
      redirect_to creditcards_path
    end
  end

  private
  def new_params
    params.require(:creditcard).permit(:card_number, :valid_month, :valid_year, :security_code).merge(user_id: current_user.id)
  end

  def set_creditcard
    @creditcard = Creditcard.find(params[:id])
  end
end

app/views/creditcards/index.html.haml
= render 'shared/top-header'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %h2.card-head
        支払い方法
      .registration-container
        .registration-container__card
          %section
            .card-content
              %h3
                クレジットカード一覧
          %section.add-card
            .add-card__content
              = link_to new_creditcard_path,class: "btn-card btn-signin" do
                %i.fas.fa-credit-card
                クレジットカードを追加する
          .about-payment
            = link_to "#" ,class: "about-payment-link" do
              支払い方法について
              %i.fas.fa-angle-right

    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'
=render 'shared/sell-btn'

app/views/creditcards/new.html.haml
= render 'shared/top-header'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %h2.card-head
        クレジットカード情報入力
      .registration-container__new
        = form_for(@creditcard) do |f|
          .registration__payment
            .field
              = f.label :card_number, "カード番号"
              %span.require 必須
              = f.text_field :card_number, class: "card-number input-default", placeholder: '半角数字のみ'
              %ul.card-list
                %li
                  = image_tag("visa.svg",size: "49x20")
                %li
                  = image_tag("master-card.svg",size: "34x20")
                %li
                  = image_tag("saison-card.svg",size: "30x20")
                %li
                  = image_tag("jcb.svg",size: "32x20")
                %li
                  = image_tag("american_express.svg",size: "21x20")
                %li
                  = image_tag("dinersclub.svg",size: "32x20")
                %li
                  = image_tag("discover.svg",size: "32x20")
            .field
              = f.label :有効期限
              %span.require 必須
              %br/
              .birthday-wrap
                .select
                  = f.select :valid_month, [], {prompt: "--"}, {class: "card-month"}
                %span 月
                .select
                  = f.select :valid_year, [], {prompt: "--"}, {class: "card-year"}
                %span 年

            .field
              = f.label :security_code, "セキュリティコード"
              %span.require 必須
              = f.text_field :security_code, class: "security-code input-default", placeholder: 'カード背面4桁もしくは3桁の番号'
              .text-right__card
                %span.card-question ?
                カード裏の番号とは？
            .actions
              = f.submit class: "btn-end", value: "追加する"


    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'
=render 'shared/sell-btn'

app/views/creditcards/show.html.haml
- breadcrumb :payment
= render "shared/top-header"
= render 'shared/breadcrumbs'
.mypage
  %main.mypage__body.clearfix
    .mypage__body__main
      %h2.card-head
        支払い方法
      .registration-container
        .registration-container__card
          %section
            .card-content
              %h3
                クレジットカード一覧
          %section.add-card
            .add-card__content
              %ul.user-card-list
                %li
                  = image_tag("visa.svg",size: "49x20")
              .add-card__content__number
                %a
                  - regexp = /\d(?=(\D*\d){4})/
                  = @creditcard.card_number.gsub(regexp, '*')
              .add-card__content__number
                - exp_month = @creditcard.valid_month.to_s
                - exp_year = @creditcard.valid_year.to_s.slice(2,3)
                %a
                  = exp_month + " / " + exp_year
              = link_to creditcard_path,method: :delete,class:"btn-cd-delete" do
                削除する
          .about-payment
            = link_to "#" ,class: "about-payment-link" do
              支払い方法について
              %i.fas.fa-angle-right

    = render 'shared/mypage-sidemenu'
= render 'shared/banner'
= render 'shared/top-footer'
=render 'shared/sell-btn'