config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  # omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get :user_logout
      get :user_signup
      get :user_products
    end

    member do
      get :identification
    end
  end

  resources :products do
    resource :product_comments, only: [:create]
    post 'my_product_comments'=> 'product_comments#my_product_comments'
    collection do
      get :confirm
      get :search
      get :get_category_children, defaults: { format: 'json' }
      get :get_category_grandchildren, defaults: { format: 'json' }
      get :get_size, defaults: { format: 'json' }
    end
    member do
      get :purchase
      patch :bought
      get :my_show
      get :unpublished
      get :sell
      get :get_size, defaults: { format: 'json' }
    end
  end

  namespace :api do
    resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
      collection do
        delete "image_destroy"
      end
    end
  end

  resources :creditcards, only: [:index, :new, :show, :destroy, :create]

  resources :categories, only: [:index, :show]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many :product_comments,dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :user
  belongs_to :category
  belongs_to :products_size, foreign_key: "size_id", optional: true
  belongs_to :brand, foreign_key: "brand_id", optional: true
  belongs_to :buyer, class_name: "User",optional: true
  enum status: {
    sell: 0, sold: 1, soldout: 2, unpublished: 3
  }, _prefix: true
  # sell 出品中、sold 売れた、soldout 売れて消える

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  def image_destroy
    image = Image.find(params[:img_id])
    if image.product.user_id == current_user.id
      image.destroy
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!,only: [:new, :purchase]
  before_action :set_product, only: [:show, :purchase, :bought, :my_show, :edit,:unpublished, :sell, :update, :destroy]
  before_action :show_product, only: [:show, :my_show]

  def index
    @lady_items = Product.includes(:images).where(category_id: Category.find(1).subtree_ids, status: 0).order(created_at: "DESC").limit(4)
    @man_items = Product.includes(:images).where(category_id: Category.find(2).subtree_ids, status: 0).order(created_at: "DESC").limit(4)
    @kids_items = Product.includes(:images).where(category_id: Category.find(3).subtree_ids, status: 0).order(created_at: "DESC").limit(4)
    @beauty_items = Product.includes(:images).where(category_id: Category.find(7).subtree_ids, status: 0).order(created_at: "DESC").limit(4)
    
    @chanel = Product.includes(:images).where(brand_id: 1, status: 0).order(created_at: "DESC").limit(4)
    @nike = Product.includes(:images).where(brand_id: 2, status: 0).order(created_at: "DESC").limit(4)
    @vuitton = Product.includes(:images).where(brand_id: 3, status: 0).order(created_at: "DESC").limit(4)
    @supreme = Product.includes(:images).where(brand_id: 4, status: 0).order(created_at: "DESC").limit(4)
  end
  
  def new
    @product = Product.new
    # @product.images.build
    2.times{@product.images.build}
    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
    end
  end

  def show
    @category_products = Product.where(category_id: @product.category_id).where.not(id: @product.id).order("id DESC").limit(6)
  end

  def my_show
  end

    # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}") #孫カテゴリーを取得
    if related_size_parent = selected_grandchild.products_sizes[0] #孫カテゴリーと紐付くサイズ（親）があれば取得
      @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
    else
      selected_child = Category.find(params[:grandchild_id]).parent #孫カテゴリーの親を取得
       if related_size_parent = selected_child.products_sizes[0] #孫カテゴリーの親と紐付くサイズ（親）があれば取得
          @sizes = related_size_parent.children #紐づいたサイズ（親）の子供の配列を取得
       end
    end
  end
  
  def create
    @product = Product.new(product_params)
    if @product.images.first&.name
      @product.save
    else
      redirect_to new_product_path
    end
  end

  def edit
    @category = @product.category
    @child_categories = Category.where('ancestry = ?', "#{@category.parent.ancestry}")
    @grand_child = Category.where('ancestry = ?', "#{@category.ancestry}")
    @parent = @product.category.root.name
  end

  def update
    if @product.update(update_product_params)
      redirect_to my_show_product_path(@product)
    else
      redirect_to edit_product_path
    end
  end

  def purchase
    redirect_to :back if @product.user.id == current_user&.id
  end

  def search
    @products = Product.where('name LIKE(?)',"%#{params[:keyword]}%").page(params[:page]).per(114)
  end

  def bought
    if @product.status == "sell" and @product.buyer_id.nil? == true
      @product.update(status: "sold", buyer_id: current_user.id)
    else
      redirect_to root_path
    end
    if @product.status == "sell" and @product.buyer_id.nil? == true
      @product.update(status: "sold", buyer_id: current_user.id)
    else
      redirect_to root_path
    end
  end

  def unpublished
    if @product.status_sell? and @product.buyer_id.nil? == true
      @product.update(status: "unpublished")
      redirect_to my_show_product_path
    else
      redirect_to root_path
    end
  end

  def sell
    if @product.status == "unpublished"
      @product.update(status: "sell")
      redirect_to my_show_product_path
    else
      redirect_to root_path
    end
  end

  def my_show
    category_id = @product.category_id
    @products = Category.find(category_id).products
    @brand_products = Product.where(brand_id: @product.brand_id).where.not(id: @product.id).order("id DESC").limit(6)
    @user_products = Product.where(user_id: @product.user.id).where.not(id: @product.id).order("id DESC").limit(6)
    @previous_product = @product.previous
    @next_product = @product.next
    @product_comments = ProductComment.new
    @comments = ProductComment.where(product_id: @product.id)
  end

  def destroy
    if @product.user_id == current_user.id
        if @product.destroy
          redirect_to  user_products_users_path, notice: '商品を削除しました'
        end
    else
      render :index
      flash[:alert] = '商品削除に失敗しました'
    end
  end

  private
  def product_params
    params.require(:product).permit(:buyer_id, :brand_id, :category_id, :shipping_date, :name, :description, :status, :price, :condition, :size_id, :shipping_method, :shipping_burden, :shipping_region, images_attributes: [:name]).merge(user_id: current_user.id)
  end

  def update_product_params
    params.require(:product).permit(:buyer_id, :brand_id, :category_id, :shipping_date, :name, :description, :status, :price, :condition, :size_id, :shipping_method, :shipping_burden, :shipping_region, images_attributes: [:name, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def show_product
    category_id = @product.category_id
    @products = Category.find(category_id).products
    @brand_products = Product.where(brand_id: @product.brand_id).where.not(id: @product.id).order("id DESC").limit(6)
    @user_products = Product.where(user_id: @product.user.id).where.not(id: @product.id).order("id DESC").limit(6)
    @previous_product = @product.previous
    @next_product = @product.next
    @product_comments = ProductComment.new
    @comments = ProductComment.where(product_id: @product.id)
  end
end

app/helpers/product_helper.rb
module ProductsHelper
  def converting_to_jpy(price)
    "¥#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def converting_to_jpy(price)
    #金額表示にカンマを入れるメソッド
    "¥#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/products/_brand-search.html.haml
.brand-index
  %ul.b-parent-wrap
    - @brands.each do |brand|
      %li.b-parent-wrap__list
        = link_to("#") do
          = brand.name

app/views/products/_category-search.html.haml
.category-index
  %ul.parent-wrap
    - @parents.each do |parent|
      %li.parent-wrap__list
        = link_to category_path(parent) do
          =parent.name
        %ul.child-wrap
          - parent.children.each do |child|
            %li.child-wrap__list
              = link_to category_path(child) do
                =child.name
              %ul.grandchild-wrap
                - child.children.each do |grandchild|
                  %li.grandchild-wrap__list
                    = link_to category_path(grandchild) do
                      =grandchild.name

app/views/products/_create-modal.html.haml
#create-modal
  #create-modalWindow
    .create-modal-message-box
      %p 出品が完了しました
      .sell-modal-body あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。
      = link_to "続けて出品する", new_product_path, class: "create-modal-btn"
      = link_to "戻る", root_path, class: "create-modal-back"

app/views/products/_item-search.html.haml
.search-main
  .search-wrapper
    .search-side
      %form.search-form
        .search-sort
          .search-sort__select
            %select.search-sort__select--order{name: "sort_order"}
              %option{value: ""} 並び替え
              %option{selected: "selected", value: "price_asc"}
                価格の安い順
              %option{value: "price_desc"}
                価格の高い順
              %option{value: "created_asc"}
                出品の古い順
              %option{value: "created_desc"}
                出品の新しい順
              %option{value: "like_desc"}
                いいね!の多い順
            -# fontawesomeは次につける
            -# %i.fa.fa-angle-down.search-sort__select--icon

        .search-dropdown-wrapper
          %h3.search-dropdown-wrapper__title 詳細検索
          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title キーワードを追加する
            %input{type: "text",class: "search-dropdown-wrapper__form--box", name: "keyword", value: "パプリカ"}
          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title カテゴリーを検索する
            %input{type: "text",class: "search-dropdown-wrapper__form--box", name: "keyword", value: "パプリカ"}
          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title ブランド名から探す
            %input{type: "text",class: "search-dropdown-wrapper__form--box", name: "keyword", value: "パプリカ"}
          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title サイズを指定する
            %input{type: "text",class: "search-dropdown-wrapper__form--box", name: "keyword", value: "パプリカ"}
          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title 価格
            %input{type: "text",class: "search-dropdown-wrapper__form--box", name: "keyword", value: "パプリカ"}
            %input{type: "text",class: "search-dropdown-wrapper__form--number1", name: "keyword", value: "￥Min"}
            %p -
            %input{type: "text",class: "search-dropdown-wrapper__form--number2", name: "keyword", value: "￥Max"}

          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title 商品の状態
            .product-state
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .product-state__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて

          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title 商品の状態
            .delivery-fee
              .delivery-fee__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .delivery-fee__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .delivery-fee__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて

          .search-dropdown-wrapper__form
            %i.fa.fa-plus.search-dropdown-wrapper__form--icon
            %h4.search-dropdown-wrapper__form--title 商品の状態
            .sales-condition
              .sales-condition__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .sales-condition__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
              .sales-condition__checkbox-list
                %input{type: "checkbox", name: "condition_all", class: "checkbox-list_all"}
                %label すべて
     
          .search-dropdown-wrapper__button
            .search-dropdown-wrapper__button--clear クリア
            .search-dropdown-wrapper__button--complete 完了

    .search-items
      .search-items__title
        = params[:keyword]
      %span の検索結果
      .search-items__number 1-132件表示
      %ul.search-items__lists
        = render partial: "product", collection:  @products

app/views/products/_item.html.haml
= link_to product_path(item.id) ,class: "item-boxes" do
  .item-box
    .item-box__photo
      = image_tag(item.images.first.name)
    .item-box__body
      .item-box__body--text
        %p
          = item.name
      .item-box__body--block
        .product-price
          %p 
            = converting_to_jpy(item.price)
        .product-evaluation
          %i.far.fa-heart.product-evaluation__heart-icon
          .product-evaluation__count
            %p 5

app/views/products/_product.html.haml
%li.search-items__lists--list
  = link_to product_path(product.id) do
    .product-box
      - if product.status == "sold"
        .product-box__sold
          .product-box__sold--text SOLD
      .product-box__photo
        = image_tag(product.images.first.name.to_s)
      .product-box__body
        .product-box__body--text
          %p
            = product.name
        .product-box__body--block
          .search-product-price
            %p 
              = converting_to_jpy(product.price)
          .search-product-evaluation
            %i.far.fa-heart.search-product-evaluation__heart-icon
            .search-product-evaluation__count
              %p 5

app/views/products/_top-header.html.haml
.top-header
  .header-in
    .header-top
      .header-logo
        = image_tag("mercari_logo.svg", size: "133.99x36", alt: "mercari")

      .header-search
        %form.header-search__input
          %textarea.header-search__input--text 何かお探しですか?
          =link_to "#", class: "header-search__input--icon" do
            = fa_icon 'search', class: "search"
            %span<>

        -# = form_for [@products] do |f|
        -#   ＝f.text_area(プロパティ名 [, オプション])
        -#   = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        -#   .form__mask
        -#     = f.label :image, class: 'form__mask__image' do
        -#       = fa_icon 'picture-o', class: 'icon'
        -#       = f.file_field :image, class: 'hidden'
        -#   = f.submit 'Send', class: 'form__submit'
    .header-bottom
      .h-left
        =link_to "#",class: "category-search" do
          = fa_icon 'list', class: "category-search__icon"
          %h2.category-search__title カテゴリーから探す
        =render 'category-search'

        =link_to "#",class: "brand-search" do
          = fa_icon 'tag', class: "brand-search__icon"
          %h2.brand-search__title ブランドから探す
        =render 'brand-search'

      .h-right
        -# - if user_signed_in?
        .h-right__list
          =link_to "#",class: "notification" do
            = fa_icon 'bell', class: "notification__icon"
            %span.notification__title お知らせ
        .h-right__list
          =link_to "#",class: "todo" do
            = fa_icon 'check', class: "todo__icon"
            %span.todo__title やることリスト
        .h-right__list
          =link_to "#",class: "mypage" do
            = image_tag("#", size: "133.99x36", alt: "my", class: "mypage__image")
            %span.mypage__title マイページ

        -# - else
        -#   =link_to "#",class: "sign-up" do
        -#     新規会員登録
        -#   =link_to "#",class: "sign-in" do
        -#     ログイン

app/views/products/bought.html.haml
.l-main-container
  = render 'shared/second_header'
  .purchase-main
    .l-purchase-container--buy-item-container
      .transact-attention
        %h3
          %i.far.fa-clock
          %span 発送をお待ちください
        %p 出品者からの発送通知をお待ちください
      .bought-head 購入が完了しました
      .purchase-content.purchase-item
        .bought--inner
          .purchase-item-image
            = image_tag @product.images[0].name.url, class: "item_photo",size: '63x64'
          %p.purchase-item-named
            = @product.name
      .purchase-content.purchase-item
        .purchase-content--inner
          .purchase-form
            = "¥ #{@product.price}"
      .purchase-content.purchase-user-info
        .purchase-content-inner
          %h3 配送先
          .purchase-user-info-text
            = "〒 #{current_user.user_address.postal_code}"
            %br
            = "#{current_user.user_address.prefecture} #{current_user.user_address.city} #{current_user.user_address.block_number} #{current_user.user_address.building}"
            %br
            = "#{current_user.user_detail.last_name}#{current_user.user_detail.first_name}"
      .purchase-content.purchase-user-info
        .purchase-content-inner
          %h4 発送通知後の流れ
          %p 商品を受けとったら
          %p 出品者の評価をしましょう。
          %p 購入代金が出品者に振り込まれます。
          %p 評価後に取引は完了します。
          =link_to "/users", class: 'purchase-info-fix' do
            %span マイページへ戻る
  .products-footer
    %nav
      %ul.clearfix
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引に関する表記
    = link_to "#", class: "single-iamge" do
      = image_tag "productsnew.png",class:"my_class"
    %p © 2019 Mercari

app/views/products/confirm.html.haml
.confirm-container
  .confirm-header
    =render '/shared/common-header'

  .confirm-main
    .buy-container
      %h2.confirm-title 購入内容の確認

      .product-wrapper
        .product-wrapper__inner
          .product-block
            = image_tag("paprica.jpg", class: "product-block__pic")
            .product-block__title 世界NO1そして世界最高の安価のパプリカ@名古屋市産

          %form.product-form
            .price-mini
              %p.price-mini__amount ¥500
              %p.price-mini__shipping-fee 送料込み

            .product-point
              %p.product-point__text ポイントはありません

            .price-main
              .price-main__text 支払い金額

              .price-main__pay ¥500

            .error-message

            .buy-button
              %input{type: "submit", value: "購入する" }

      .buyer-wrapper
        .user-info
          %h3.user-info__title 配送先
          %ul.user-info__text
            %li 〒555-5555
            %li ナメック星ナメック市ナメック町1-1-1-1
            %li フリーザ

          .user-info__fix
            =link_to("#", class: "user-info__fix" )do
              %p.user-info__fix--text 変更する
              = fa_icon 'chevron-right', class: "user-info__fix--arrow-right"

      .payment
        .payment-info
          %h3.payment-info__title 支払い方法
          %ul.payment-info__text
            %li **********3233
            %li 07/19
            %li 
              = image_tag('visa.svg',class: "payment-info__image")
          .payment-info__fix
            =link_to "#" do
              %p.payment-info__fix--text 変更する
              = fa_icon 'chevron-right', class: "payment-info__fix--arrow-right"

  .confirm-footer
    =render 'devise/registrations/footer'

app/views/products/index.html.haml
=render 'shared/top-header'
=render 'main'
=render 'shared/banner'
=render 'shared/top-footer'
=render 'shared/sell-btn'

app/views/products/my_show.html.haml
.detail-container
  =render 'shared/top-header'
  %main.mypage__body.clearfix
    .delete-detail-box
      .detail-box
        %h1.item-name
          = @product.name
        .detail-box__main
          .detail-box__main__image
            .top-image
              .is-slider
                - @product.images.each do |img|
                  .is-slider__item
                    = image_tag(img.name.url, height: '300px', width: '300px', class: 'item-image-active')
                    - if @product.status == "sold"
                      .category-box__sold
                        .category-box__sold--text SOLD
                    - elsif @product.status == "unpublished"
                      .category-box__unpublished
                        .category-box__unpublished--text
                          %p 公開停止中
              .is-thumbnails
                - @product.images.each do |img|
                  .is-thumbnails__item
                    = image_tag(img.name.url, height: '60px', width: '60px', class: 'item-image')
          %table.detail-box__main__table
            %tbody
              %tr
                %th 出品者
                %td
                  = link_to root_path do
                    = @product.user.nickname
                  .user-ratings
                    .user-ratings__list
                      %i.fas.fa-laugh
                      %span 0
                    .user-ratings__list
                      %i.fas.fa-meh
                      %span 0
                    .user-ratings__list
                      %i.fas.fa-frown
                      %span 999
              %tr
                %th カテゴリー
                %td
                  = link_to root_path do
                    - if @product.category.present?
                      = @product.category.root.name
                      %br > #{@product.category.parent.name}
                      > #{@product.category.name}
                  
              %tr
                %th ブランド
                %td
                  = link_to root_path do
                    - if @product.brand.present?
                      = @product.brand.name
              %tr
                %th 商品のサイズ
                %td
                  - if @product.products_size.present?
                    = @product.products_size.size
              %tr
                %th 商品の状態
                %td
                  = @product.condition
              %tr
                %th 配送料の負担
                %td 
                  = @product.shipping_burden
              %tr
                %th 配送の方法
                %td 
                  = @product.shipping_method
              %tr
                %th 配送元地域
                %td 
                  = link_to root_path do
                    = @product.shipping_region
                
              %tr
                %th 発送日の目安
                %td 
                  = @product.shipping_date

        .detail-box__price
          %span.item-price
            = converting_to_jpy(@product.price)
          %span.item-tax (税込)
          %span.shipping-fee 送料込み
      
      .item-change-box
        = link_to '商品の編集', edit_product_path, class: 'btn-edit'
        %p.text-center or
        - if @product.status == "sell"
          = link_to '商品を一旦停止する', unpublished_product_path, class: 'btn-stop'
        - elsif @product.status == "unpublished"
          = link_to '商品を再開する', sell_product_path, class: 'btn-restart'
        -# = button_tag '商品を一旦停止する', class: 'btn-stop'
        %button#modal-open-btn この商品を削除する
        = link_to '', product_path, method: :delete, class: 'btn-delete', id: 'item-delete-btn'
        = render "delete-modal"
      .item-comments
        .item-comments__container
          .item-comments__container__message
            %ul.messeage-items
              = render partial: "shared/comment", collection: @comments
          .item-comments__container__message
            .form-test
              %p
                相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
              = form_for([@product, @product_comments], url:  product_my_product_comments_path(@product.id)) do |f|
                = f.text_area :comment, class:'textarea-test'
                = f.submit "コメントする", class:'btn-comment'
  =render 'shared/banner'
  =render 'shared/top-footer'

app/views/products/purchase.html.haml
.l-main-container
  = render 'shared/second_header'
  .purchase-main
    .l-purchase-container--buy-item-container
      %h2.purchase-head 購入内容の確認
      .purchase-content.purchase-item
        .purchase-content--inner
          .purchase-content-image
            = image_tag @product.images[0].name.url, class: "item_photo",size: '63x64'
          %p.purchase-item-name
            = @product.name
          .purchase-form
            .purchase-price-ja 
              = "¥ #{@product.price}"
              .product-shipping-fee 送料込み
            %ul.purchase-accordion.not-have
              %li.accordion-parent
                .accordion-toggle ポイントはありません
            %ul.purchase-price-table
              %li.purchase-price-row
                .purchase-price-cell 支払い金額
                .purchase-price-cell
                  %span
                  = "¥ #{@product.price}"
            = link_to '購入する', bought_product_path, method: :PATCH, class: 'purchase-btn'
      .purchase-content.purchase-user-info
        .purchase-content-inner
          %h3 配送先
          .purchase-user-info-text
            = "〒 #{current_user.user_address.postal_code}"
            %br
            = "#{current_user.user_address.prefecture} #{current_user.user_address.city} #{current_user.user_address.block_number} #{current_user.user_address.building}"
            %br
            = "#{current_user.user_detail.last_name}#{current_user.user_detail.first_name}"
          =link_to "", class: 'purchase-user-info-fix' do
            %span 変更する
            = fa_icon "angle-right"
      .purchase-content.purchase-user-info
        .purchase-content-inner
          %h3 支払い方法
          =link_to "", class: 'purchase-user-info-fix' do
            %span 変更する
            = fa_icon "angle-right"
  .products-footer
    %nav
      %ul.clearfix
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引に関する表記
    = link_to "#", class: "single-iamge" do
      = image_tag "productsnew.png",class:"my_class"
    %p © 2019 Mercari

app/views/products/search.html.haml
= render 'shared/top-header'
- breadcrumb :search
= render 'shared/breadcrumbs'
= render 'item-search'
= render 'shared/banner'
= render 'shared/top-footer'
= render 'shared/sell-btn'

app/views/products/show.html.haml
.detail-container
  =render 'shared/top-header'
  =render 'detail'
  =render 'shared/banner'
  =render 'shared/top-footer'